name: Apsis CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Litestream
      run: wget --quiet https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb && sudo dpkg -i litestream-v0.3.13-linux-amd64.deb

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: pip3 install --upgrade pip 'setuptools>=61'

    - name: Install package
      run: pip3 install -e .[dev]

    - name: Install procstar from latest release
      run: pip3 install $(gh release view --repo apsis-scheduler/procstar --json assets --jq '.assets[] | select(.name | endswith(".whl")) | .url')
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run Python unit tests
      run: pytest test/unit -m "not local_ssh"

    - name: Run Python integration tets
      run: pytest test/int -m "not local_ssh"

