name: Apsis CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Litestream
      run: wget --quiet https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb && sudo dpkg -i litestream-v0.3.13-linux-amd64.deb

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Install dependencies
      # extra index-url is for using procstar repository as a pypi index via Github
      # Pages
      run: uv sync --extra-index-url https://apsis-scheduler.github.io/procstar/simple

    - name: Run Python unit tests
      run: uv run pytest test/unit -m "not local_ssh"

    - name: Run Python integration tests
      run: uv run pytest test/int -m "not local_ssh"

